### ISSUE TITLE
cp1252 character problem

### ISSUE THREAD

**Issue by oxsotus** [ikkentim/SampSharp#214] opened 2017-08-30 09:16 UTC
Dear ikkentim,

I have a problem with the accents.
I tried multiple code pages but no ones work.
If I send text from the server to the client it works, but if the client writes something then the characters with accents are disappered.
A picture of the problem:

![character_problem](https://user-images.githubusercontent.com/31470848/29864846-2fee4b06-8d74-11e7-9481-7bfeb1c4a4e7.png)

cp12512 the good code page for me beacause that contains the characters I want to use:
íöüóőúáéű
Can you help me?

**Comment by ikkentim** [comment] 2017-08-30 10:46
Are you using 0.7(the current version on NuGet)? This will be fixed in the next release, 0.8.

**Comment by oxsotus** [comment] 2017-08-30 11:53
Yes, I use 0.7
(SampSharp-0.7.6221.37952)
Thank you!

**Comment by ikkentim** [comment] 2017-09-07 18:12
This should be fixed in the newly released 0.8.0-alpha1 version. Please note this is a prerelease that should not yet be used on a production/public server.

**Comment by ikkentim** [comment] 2017-09-07 18:13
Also closing this as a duplicate of #190

**Closed by ikkentim** 2017-09-07 18:13 UTC
