### ISSUE TITLE
[ECS] Components not getting destroyed

### ISSUE THREAD

**Issue by TheFuseGamer** [ikkentim/SampSharp#357] opened 2020-06-07 17:29 UTC
`component.DestroyComponents<T>()` and `component.Destroy()` don't seem to call OnDestroyComponent() or setting IsComponentAlive to false. Example:

```c#
TestComponent test = player.AddComponent<TestComponent>();
player.DestroyComponents<TestComponent>();
player.SendClientMessage("IsComponentAlive: " + test.IsComponentAlive); // output: IsComponentAlive: true
test.Destroy();
player.SendClientMessage("IsComponentAlive: " + test.IsComponentAlive); // output: IsComponentAlive: true
```

**Comment by ikkentim** [comment] 2020-06-08 14:07
Duplicate of #334, will leave this one open till the PR is merged.

**Closed** 2020-06-24 07:35 UTC
