### ISSUE TITLE
Problems with reading BaseVehicle fields

### ISSUE THREAD

**Issue by DENLN** [ikkentim/SampSharp#242] opened 2018-02-08 18:16 UTC
Hello.

I have Timer in GameMode.cs

```
namespace AscensionMode
protected override async void OnInitialized(EventArgs e)
{
     base.OnInitialized(e);

     timerScanSpeedCar = new Timer(100, true);
     timerScanSpeedCar.Tick += TimerScanSpeedCar_Tick;
```
```
private static void TimerScanSpeedCar_Tick(object sender, EventArgs e)
{
     Systems.carSystem.CCarSystem.CarScanSpeed();
}
```
**and problem in this method**
```
namespace AscensionMode.Systems.carSystem
public static void CarScanSpeed()
{
    Console.WriteLine("Tick: " + DateTime.Now.TimeOfDay.ToString());
    for (int i = 0; i < AllCarsList.Count; i++)
    {
        BaseVehicle veh = BaseVehicle.Find(AllCarsList[i].carID);

        try
        {
            AllCarsList[i].SpeedTextDraw.Text = Math.Round(Math.Sqrt(veh.Velocity.X * veh.Velocity.X + veh.Velocity.Y * veh.Velocity.Y + veh.Velocity.Z * veh.Velocity.Z) * 170, 0).ToString();
        }
        catch (Exception exx)
        {
            Console.WriteLine(exx.Message.ToString());
        }
    }
}
```
![](https://i.imgur.com/B4njwY0.png)
**.Net Core 2.0**

**Comment by ikkentim** [comment] 2018-02-09 13:41
Could you also print the exception's stack trace so we can see what's causing the error?

**Comment by DENLN** [comment] 2018-02-09 16:27
**CCarSystem.cs:line 6**
`AllCarsList[i].SpeedTextDraw.Text = Math.Round(Math.Sqrt(veh.Velocity.X * veh.Velocity.X + veh.Velocity.Y * veh.Velocity.Y + veh.Velocity.Z * veh.Velocity.Z) * 170, 0).ToString();`

**duplicate type name within assembly.**
```at System.Reflection.Emit.ModuleBuilder.CheckTypeNameConflict(String strTypeName, Type enclosingType)
at System.Reflection.Emit.AssemblyBuilderData.CheckTypeNameConflict(String strTypeName, TypeBuilder enclosingType)
at System.Reflection.Emit.TypeBuilder.Init(String fullname, TypeAttributes attr, Type parent, Type[] interfaces, ModuleBuilder module, PackingSize iPackingSize, Int32 iTypeSize, TypeBuilder enclosingType)
at System.Reflection.Emit.ModuleBuilder.DefineType(String name, TypeAttributes attr, Type parent)
at SampSharp.Core.Natives.NativeObjects.NativeObjectProxyFactory.CreateInstance(Type type, Object[] arguments) in D:\DENLN\SampSharp-master\src\SampSharp.Core\Natives\NativeObjects\NativeObjectProxyFactory.cs:line 66
at SampSharp.Core.Natives.NativeObjects.NativeObjectProxyFactory.CreateInstance[T](Object[] arguments) in D:\DENLN\SampSharp-master\src\SampSharp.Core\Natives\NativeObjects\NativeObjectProxyFactory.cs:line 50
at SampSharp.Core.Natives.NativeObjects.NativeObjectSingleton`1.get_Instance() in D:\DENLN\SampSharp-master\src\SampSharp.Core\Natives\NativeObjects\NativeObjectSingleton`1.cs:line 30
at SampSharp.GameMode.World.BaseVehicle.get_Velocity() in D:\DENLN\SampSharp-master\src\SampSharp.GameMode\World\BaseVehicle.cs:line 128
at AscensionMode.Systems.carSystem.CCarSystem.CarScanSpeed() in D:\DENLN\SampSharp-master\src\TestMode.DotNetCore\Systems\carSystem\CCarSystem.cs:line 60
```

   
and
   
**Index was out of range. Must be non-negative and less than the size of the collection.**
```at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
at System.BitConverter.ReadInt32(Byte[] value, Int32 startIndex)
at SampSharp.Core.Communication.ValueConverter.ToSingle(Byte[] buffer, Int32 startIndex) in D:\DENLN\SampSharp-master\src\SampSharp.Core\Communication\ValueConverter.cs:line 188
at SampSharp.Core.Natives.NativeParameterInfo.GetReferenceArgument(Byte[] response, Int32& index, Int32 length, IGameModeClient gameModeClient) in D:\DENLN\SampSharp-master\src\SampSharp.Core\Natives\NativeParameterInfo.cs:line 162
at SampSharp.Core.Natives.Native.Invoke(Object[] arguments) in D:\DENLN\SampSharp-master\src\SampSharp.Core\Natives\Native.cs:line 107
at SampSharp.Core.Natives.Native.InvokeBool(Object[] arguments) in D:\DENLN\SampSharp-master\src\SampSharp.Core\Natives\Native.cs:line 147
at VehicleInternalProxyClass.GetVehicleVelocity(Int32 , Single& , Single& , Single& )
at SampSharp.GameMode.World.BaseVehicle.get_Velocity() in D:\DENLN\SampSharp-master\src\SampSharp.GameMode\World\BaseVehicle.cs:line 129
at AscensionMode.Systems.carSystem.CCarSystem.CarScanSpeed() in D:\DENLN\SampSharp-master\src\TestMode.DotNetCore\Systems\carSystem\CCarSystem.cs:line 60
```

**Comment by ikkentim** [comment] 2018-02-09 19:26
Which sampsharp version are you using?

**Comment by DENLN** [comment] 2018-02-09 19:32
Last: 0.8.0-alpha6 :)

**Comment by d0Nt** [comment] 2018-02-11 09:44
I have the same issue with .net core project. All natives(testes with vehicles) which returns data by out referece fails.

**Comment by d0Nt** [comment] 2018-02-11 09:51
That's strange, but when I created empty gamemode for testing(same .net core) everything works fine there.

**Comment by DENLN** [comment] 2018-02-11 11:04
I noticed a very strange work of timers
Perhaps this will explain the problems with the reading fields

I wrote that I have one timer

```
namespace AscensionMode
protected override async void OnInitialized(EventArgs e)
{
     base.OnInitialized(e);

     timerScanSpeedCar = new Timer(2000, true);
     timerScanSpeedCar.Tick += TimerScanSpeedCar_Tick;
```
```
private static void TimerScanSpeedCar_Tick(object sender, EventArgs e)
{
     Systems.carSystem.CCarSystem.CarScanSpeed();
}

```
When you start the server, everything is fine, the timer runs in a single instance
But when I add transport, the timer starts to malfunction

> Logs:
> start server
> Tick: 13:43:36.3975986
> Tick: 13:43:38.3924584
> Tick: 13:43:40.3899654
> 
> Create car: 1
> Tick: 13:43:42.3924959: 100
> Tick: 13:43:42.4893040: 100
> 
> Tick: 13:43:46.3844033: 100
> Tick: 13:43:46.3902848: 100
> 
> Tick: 13:43:50.3848201: 100
> Tick: 13:43:50.3904908: 100
> 
> Tick: 13:43:54.3836295: 98,1
> Tick: 13:43:54.3908518: 96,2
> Tick: 13:43:54.3984313: 94,3
> Tick: 13:43:54.4121135: Crash
> 
> Tick: 13:44:02.3907043: 88,8
> Tick: 13:44:02.4000018: Crash
> Tick: 13:44:02.4051215: 83,3
> Tick: 13:44:02.4129490: Crash
> 
> Tick: 13:44:10.3844234: 80,99999
> Tick: 13:44:10.3900360: 78,69999
> Tick: 13:44:10.3970383: 76,39999
> Tick: 13:44:10.4133943: Crash
> 
> 
> Create car: 2
> Tick: 13:44:52.3833486: 61,59997
> Tick: 13:44:52.3889358: 61,39997
> Tick: 13:44:52.3894504: 91,3
> Tick: 13:44:52.3951245: 61,19997
> Tick: 13:44:52.3974752: 91,3
> Tick: 13:44:52.4003842: 60,99997
> Tick: 13:44:52.4008593: 91,3
> Tick: 13:44:52.4128367: Crash
> Tick: 13:44:52.4239357: Crash
> Tick: 13:44:52.4287368: 91,3
> 
> 
> Tick: 13:45:02.3855774: 60,79996
> Tick: 13:45:02.3911427: 60,59996
> Tick: 13:45:02.3914343: 91,3
> Tick: 13:45:02.3967337: 60,39996
> Tick: 13:45:02.3969605: 91,3
> Tick: 13:45:02.4021181: 60,19996
> Tick: 13:45:02.4023202: 91,3
> Tick: 13:45:02.4084634: Crash
> Tick: 13:45:02.4189094: Crash
> Tick: 13:45:02.4240123: 91,3

feeling that the timer is multiplying

**Comment by DENLN** [comment] 2018-02-11 11:28
I wrote that I have one timer
```
protected override async void OnInitialized(EventArgs e)
{
     base.OnInitialized(e);

     timerScanSpeedCar = new Timer(2000, true);
     timerScanSpeedCar.Tick += TimerScanSpeedCar_Tick;
```
```
private static void TimerScanSpeedCar_Tick(object sender, EventArgs e)
{
     Systems.carSystem.CCarSystem.CarScanSpeed();
}

```
```
public static void CarScanSpeed()
{
    Console.WriteLine("Tick: " + DateTime.Now.TimeOfDay.ToString());
```
When i start the server, everything is fine, the timer writes once every 2 seconds
but when creating transport, the taimen begins to multiply

> start server
> Tick: 14:16:46.9597294: done
> Tick: 14:16:48.9594920: done
> Tick: 14:16:50.9576959: done
> Tick: 14:16:52.9612643: done
> 
> 
> Create car: 1
> Tick: 14:16:55.1381052: done
> Tick: 14:16:55.1454526: crash
> 
> Tick: 14:17:00.9623884: done
> Tick: 14:17:00.9683359: done
> 
> Tick: 14:17:04.9579962: done
> Tick: 14:17:04.9688275: crash
> 
> 
> Create car: 2
> Tick: 14:17:12.9584278: done
> Tick: 14:17:12.9642271: crash
> Tick: 14:17:12.9701769: done
> 
> Tick: 14:17:18.9568808: done
> Tick: 14:17:18.9638668: done
> Tick: 14:17:18.9697029: crash
> 
> 
> Create car: 3
> Tick: 14:17:24.9580516: done
> Tick: 14:17:24.9655917: crash
> Tick: 14:17:24.9714064: done
> Tick: 14:17:24.9783499: done
> 
> Tick: 14:17:32.9614418: done
> Tick: 14:17:32.9670552: done
> Tick: 14:17:32.9774526: crash
> Tick: 14:17:32.9833202: done

Why does the timer multiply?

**Comment by DENLN** [comment] 2018-02-11 14:56
I replaced the timers with a thread structure
**And it works perfectly**
The problem is the timers. they multiply
```
ThreadScanSpeed = new Thread(() =>
{
	while (true)
	{
		try
		{
			Systems.carSystem.CCarSystem.CarScanSpeed();
		}
		catch (Exception)
		{
			Console.WriteLine("Crash");
		}
		Thread.Sleep(50);
	}
});
ThreadScanSpeed.SetApartmentState(ApartmentState.MTA);
ThreadScanSpeed.Start();
```

**Comment by d0Nt** [comment] 2018-02-11 17:40
Yup, sampsharp timers seems faulty in 0.8.0

**Comment by ikkentim** [comment] 2018-02-11 18:32
Hmm I'll try and see what's going on

**Comment by d0Nt** [comment] 2018-02-11 18:43
I tried to fix it. I found that if you set timer.NextTick inside TimerController.OnTick everything works fine.
Maybe that will help
                else if (timer.NextTick <= now)
                {
                    timer.NextTick = now+timer.Interval;
                    timer.PerformTick();
                }

**Comment by d0Nt** [comment] 2018-02-11 19:26
Timer issues fixed(with my built plugin), but there still exist random "System.ArgumentOutOfRangeException: 'Index was out of range. Must be non-negative and less than the size of the collection.'" exceptions.

**Comment by d0Nt** [comment] 2018-02-16 15:29
This could be the case?

**Comment by ikkentim** [comment] 2018-02-17 16:19
Hmm this is very odd :/ It _should_ consistently give the right values back, and I don't see why there would be any data loss between server <> sampsharp... If you have a good way of reproducing the error, please let me know. I hope to be able to put some time into this issue soon.

**Comment by d0Nt** [comment] 2018-02-17 16:24
Ok, I will try.

**Comment by d0Nt** [comment] 2018-02-17 17:14
System.ArgumentOutOfRangeException: 'Index was out of range. Must be non-negative and less than the size of the collection.'

with: https://github.com/d0Nt/TestException

**Comment by ikkentim** [comment] 2018-05-21 19:59
I've been running this for a few hours without a single error:
```
          BaseVehicle.Create(VehicleModelType.Alpha, Vector3.One, 0, -1, -1);
            BaseVehicle.Create(VehicleModelType.Alpha, Vector3.One * 2, 0, -1, -1);
            BaseVehicle.Create(VehicleModelType.Alpha, Vector3.One * 3, 0, -1, -1);
            BaseVehicle.Create(VehicleModelType.Alpha, Vector3.One * 4, 0, -1, -1);

            var timer = new Timer(100, true, true);
            timer.Tick += (sender, args) =>
            {
               Console.WriteLine("Tick: " + DateTime.Now.TimeOfDay.ToString());
                BaseVehicle.Find(999);

                try
                {
                    foreach (var v in BaseVehicle.All)
                    {
                        var pos = v.Position;
                        Console.WriteLine(pos);
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                }
            };
```

**Comment by ikkentim** [comment] 2018-05-28 16:55
Been able to reproduce this now with code from  https://github.com/d0Nt/TestException .

**Comment by ikkentim** [comment] 2018-05-28 17:09
All right, the timer issue and the "duplicate type name within assembly" error have been fixed in the previous version. Closing this issue in favor of issue #256 since this issue here got a bit messy with 3 different bugs

**Closed by ikkentim** 2018-05-28 17:09 UTC
Labels: bug
