### ISSUE TITLE
Player does not spawn after gamemode restart when creating vehicle in OnInitialized callback

### ISSUE THREAD

**Issue by UareBugged** [ikkentim/SampSharp#271] opened 2018-07-01 09:41 UTC
OnConnected callback is called but class select immediately disappears after showing and player is not being spawned. Both gamemode, samp-server and client have to be restarted.

**Comment by ikkentim** [comment] 2018-07-05 20:19
This has been improved 9baece10c4b552fbf9e2ed17a43fbbd5f82b013a but a bug can still sometimes occur where the class selection will not appear. 

This seems is caused by some kind of SA-MP bug where filterscripts are not properly unloaded.

**Comment by ikkentim** [comment] 2020-01-15 21:35
Should be fixed with 5c63c8985fb46bdbb04693dd808cb5a2e2fec798

**Closed by ikkentim** 2020-01-15 21:35 UTC
Labels: area-intermission, bug
